package com.epam.finaltask.service;

import java.math.BigDecimal;
import java.util.UUID;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.epam.finaltask.dto.UserDTO;
import com.epam.finaltask.mapper.UserMapper;
import com.epam.finaltask.model.Role;
import com.epam.finaltask.model.User;
import com.epam.finaltask.repository.UserRepository;

@Service
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final UserMapper userMapper;

    public UserServiceImpl(UserRepository userRepository,
                           PasswordEncoder passwordEncoder,
                           UserMapper userMapper) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.userMapper = userMapper;
    }

    @Override
    public UserDTO register(UserDTO userDTO) {
        if (userRepository.existsByUsername(userDTO.username())) {
            throw new IllegalArgumentException("Username already exists");
        }

        User user = userMapper.toUser(userDTO);
        // ensure id is generated by DB
        user.setId(null);

        // encode password
        user.setPassword(passwordEncoder.encode(userDTO.password()));

        // role (default ROLE_USER)
        if (userDTO.role() != null) {
            user.setRole(Role.valueOf(userDTO.role()));
        } else {
            user.setRole(Role.ROLE_USER);
        }

        // active by default
        user.setActive(true);

        // optional balance
        if (userDTO.balance() != null) {
            user.setBalance(BigDecimal.valueOf(userDTO.balance()));
        }

        User saved = userRepository.save(user);
        return userMapper.toUserDTO(saved);
    }

    @Override
    public UserDTO updateUser(String username, UserDTO userDTO) {
        User user = userRepository.findUserByUsername(username)
                .orElseThrow(() -> new IllegalArgumentException("User not found"));

        if (userDTO.phoneNumber() != null) {
            user.setPhoneNumber(userDTO.phoneNumber());
        }
        if (userDTO.balance() != null) {
            user.setBalance(BigDecimal.valueOf(userDTO.balance()));
        }
        if (userDTO.password() != null) {
            user.setPassword(passwordEncoder.encode(userDTO.password()));
        }

        User saved = userRepository.save(user);
        return userMapper.toUserDTO(saved);
    }

    @Override
    public UserDTO getUserByUsername(String username) {
        User user = userRepository.findUserByUsername(username)
                .orElseThrow(() -> new IllegalArgumentException("User not found"));
        return userMapper.toUserDTO(user);
    }

    /**
     * Change only the account status (active / blocked) based on UserDTO.active.
     * Does NOT overwrite the whole user object anymore.
     */
    @Override
    public UserDTO changeAccountStatus(UserDTO userDTO) {
        if (userDTO.id() == null) {
            throw new IllegalArgumentException("User id is required");
        }

        UUID id = UUID.fromString(userDTO.id());

        User existing = userRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("User not found"));

        // we expect active to be provided in DTO
        existing.setActive(userDTO.active());

        User saved = userRepository.save(existing);
        return userMapper.toUserDTO(saved);
    }

    @Override
    public UserDTO blockUser(String id) {
        User user = userRepository.findById(UUID.fromString(id))
                .orElseThrow(() -> new IllegalArgumentException("User not found"));
        user.setActive(false);
        return userMapper.toUserDTO(userRepository.save(user));
    }

    @Override
    public UserDTO unblockUser(String id) {
        User user = userRepository.findById(UUID.fromString(id))
                .orElseThrow(() -> new IllegalArgumentException("User not found"));
        user.setActive(true);
        return userMapper.toUserDTO(userRepository.save(user));
    }

    @Override
    public UserDTO getUserById(UUID id) {
        User user = userRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("User not found"));
        return userMapper.toUserDTO(user);
    }
}
